### ISSUE TITLE
Links issue

### ISSUE THREAD

**Issue by ilyasbabu** [Congregalis/question_bank#10]
The links you provided for demo and api can be only accessed on your local machine. Kindly host it to show others✨

**Comment by Congregalis** [comment]
I already hosted it on [http://101.35.202.174/qbank](http://101.35.202.174/qbank) and [http://101.35.202.174:8000/](http://101.35.202.174:8000/). It's just that there is no domain name bound. 

And I think the link works fine. If there have any problems, just leave comments 😊

**Comment by ilyasbabu** [comment]
Try copying this link and open this in any other system other than that you are using now. Then you may understand what I'm trying to say☺️

**Comment by Congregalis** [comment]
I know what you are talking about. Maybe your country blocked some IP address in my country(I'm in China). I deployed this service on the server I bought, and all of my  friends in my country can visit it with no trouble. I'm sorry you can't access it. Maybe you can deploy it on your own.

**Comment by ilyasbabu** [comment]
Btw you can't host on an ip address itself, there should be a domain
